// Generated by CoffeeScript 1.8.0
(function() {
  var Board;

  module.exports = Board = (function() {
    function Board(gameId, numOfSpaces, players) {
      var _i;
      this.gameId = gameId;
      this.players = players;
      this.Spaces = {};
      console.log(players);
      for (_i = 1; 1 <= numOfSpaces ? _i <= numOfSpaces : _i >= numOfSpaces; 1 <= numOfSpaces ? _i++ : _i--) {
        this.Spaces[_i] = {
          Space: {
            num: _i,
            text: "space" + _i
          }
        };
      }
    }

    return Board;

  })();

}).call(this);
