// Generated by CoffeeScript 1.8.0
(function() {
  var fs, http, myGame, socketio;

  fs = require('fs');

  http = require('http');

  socketio = require('socket.io');

  myGame = http.createServer(function(request, response) {
    response.writeHead(200, {
      'Content-type': 'text/html'
    });
    return fs.readFile("" + __dirname + "/index.html", function(err, data) {
      if (err) {
        response.writeHead(500);
        response.end("no index.html");
      }
      return response.end(data);
    });
  });

  myGame.listen(3000, function() {
    return console.log("Welcome server started on\n localhost:3000");
  });

  myGame.socket = socketio.listen(myGame);

}).call(this);
