// Generated by CoffeeScript 1.8.0
(function() {
  var app, fs, handler, io;

  fs = require('fs');

  handler = function(req, res) {
    return fs.readFile(__dirname + '/index.html', function(err, data) {
      if (err != null) {
        res.writeHead(500);
        res.end('Error loading index.html');
      }
      res.writeHead(200);
      return res.end(data);
    });
  };

  app = require('http').createServer(handler);

  io = require('socket.io')(app);

  app.listen(3000, function() {
    return console.log('Server listening on 3000');
  });

  io.on('connection', function(socket) {
    socket.emit('welcome', "Welcome new User");
    return socket.on('my other event', function(data) {
      return console.log(data);
    });
  });

  module.exports = app;

}).call(this);
