// Generated by CoffeeScript 1.8.0
(function() {
  var User,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = User = (function() {
    var _USERCOUNT;

    _USERCOUNT = 0;

    function User(name) {
      this.name = name;
      this.createGame = __bind(this.createGame, this);
      this.id = _USERCOUNT++;
      if (this.name == null) {
        this.name = "user" + this.id;
      }
      this.coinsTotal = 0;
    }

    User.prototype.createGame = function(length) {
      var Game, game;
      Game = require('./Game.coffee');
      game = new Game(this.id, length);
      console.log("game is created");
      return game;
    };

    return User;

  })();

}).call(this);
