// Generated by CoffeeScript 1.8.0
(function() {
  var body, coffeescript, css, div, head, html, js, main, myCanvas, myFooter, myHead, mySection, raw, render, renderable, script, teacup, template, title;

  teacup = require('teacup');

  renderable = teacup.renderable, render = teacup.render, raw = teacup.raw, js = teacup.js, css = teacup.css, html = teacup.html, head = teacup.head, title = teacup.title, body = teacup.body, div = teacup.div, script = teacup.script, coffeescript = teacup.coffeescript;

  mySection = renderable(function() {
    var h1, section;
    section = teacup.section, h1 = teacup.h1;
    return section('#testSection', function() {
      return h1("This is a Section Title");
    });
  });

  myCanvas = renderable(function() {
    var canvas, h1, section;
    section = teacup.section, h1 = teacup.h1, canvas = teacup.canvas;
    section('#CanvasSection', function() {
      h1('This is the Canvas entry');
      return canvas('#myCanvas', {
        width: 400,
        height: 400
      });
    });
    return script({
      type: 'text/coffee-script',
      src: './User.coffee'
    });
  });

  myFooter = renderable(function() {
    var footer, p;
    p = teacup.p, footer = teacup.footer, script = teacup.script;
    return footer(function() {
      p('this is a footer');
      return script({
        src: 'coffee-script.js'
      });
    });
  });

  module.exports = renderable(function(_arg) {
    _arg;
    return html(function() {
      head(function() {
        title('Teacup');
        script({
          src: "http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"
        });
        return script({
          src: "teacup.js"
        });
      });
      body(function() {
        div('#app');
        return myCanvas(function() {});
      });
      return myFooter(function() {});
    });
  });

  template = renderable(function(items) {
    return ul(function() {
      var item, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        _results.push(li(item));
      }
      return _results;
    });
  });

  myHead = renderable(function() {
    head = teacup.head, title = teacup.title, script = teacup.script;
    return head(function() {
      title('Welcome');
      return script({
        src: '/js/client/client.js'
      });
    });
  });

  main = renderable(function() {
    var h1, p;
    h1 = teacup.h1, p = teacup.p, div = teacup.div;
    h1("This is a Body Title");
    mySection(function() {});
    div('#testdiv', function() {
      return p('this div renders');
    });
    myCanvas(function() {});
    return myFooter(function() {});
  });

}).call(this);
