// Generated by CoffeeScript 1.8.0
(function() {
  var Server, app, express, fs, handler, http, io, numOfUsers, teacup, users, _;

  fs = require('fs');

  _ = require('lodash');

  handler = function(req, res) {
    return fs.readFile(__dirname + '/index.html', function(err, data) {
      if (err != null) {
        res.writeHead(500);
        res.end('Error loading index.html');
      }
      res.writeHead(200, {
        "Content-Type": "text/html"
      });
      return res.end(data);
    });
  };

  http = require('http');

  express = require('express');

  teacup = require('teacup/lib/express.js');

  app = express();

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'coffee');

  app.engine("coffee", require('teacup/lib/express').renderFile);

  app.use(express["static"](__dirname + '/../public'));

  app.use(express["static"](__dirname + '/../coffee'));

  app.get('/', function(req, res) {
    return res.render('index.coffee');
  });

  Server = http.createServer(app).listen(3000, function() {
    return console.log('Server listening on 3000');
  });

  io = require('socket.io')(Server);

  users = {};

  numOfUsers = _.size(users);

  io.on('connection', function(socket) {
    socket.emit('welcome', "Welcome new User");
    return socket.on('my other event', function(data) {
      return console.log(data);
    });
  });

  module.exports = {
    app: app,
    Server: Server
  };

}).call(this);
